# Generated by Django 6.0.6 on 2026-06-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(db_index=True, max_length=10, unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=10)),
                ('south', models.FloatField()),
                ('west', models.FloatField()),
                ('north', models.FloatField()),
                ('east', models.FloatField()),
                ('population', models.IntegerField(blank=True, null=True)),
                ('median_income', models.IntegerField(blank=True, null=True)),
                ('median_home_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('zillow', 'Zillow'), ('realtor', 'Realtor'), ('redfin', 'Redfin'), ('other', 'Other')], default='zillow', max_length=50)),
                ('provider_listing_id', models.CharField(db_index=True, max_length=255)),
                ('zpid', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('detail_url', models.URLField(blank=True, default='', max_length=500)),
                ('building_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_building', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, default='')),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=10)),
                ('zipcode', models.CharField(db_index=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('first_seen', models.DateField(auto_now_add=True)),
                ('last_seen', models.DateField(auto_now=True)),
            ],
            options={
                'unique_together': {('provider_listing_id', 'source')},
            },
        ),
        migrations.CreateModel(
            name='PropertySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('status_type', models.CharField(blank=True, default='', max_length=100)),
                ('status_text', models.CharField(blank=True, default='', max_length=255)),
                ('min_rent', models.IntegerField(blank=True, null=True)),
                ('max_rent', models.IntegerField(blank=True, null=True)),
                ('availability_count', models.IntegerField(blank=True, null=True)),
                ('availability_date', models.CharField(blank=True, default='', max_length=50)),
                ('photo_count', models.IntegerField(default=0)),
                ('has_3d_model', models.BooleanField(default=False)),
                ('is_featured_listing', models.BooleanField(default=False)),
                ('days_on_zillow', models.IntegerField(blank=True, null=True)),
                ('rent_zestimate', models.IntegerField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyUnitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('room_for_rent', models.BooleanField(default=False)),
                ('property_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.propertysnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('rent_growth', 'Rent Growth'), ('rent_drop', 'Rent Drop'), ('inventory', 'Inventory'), ('heatmap', 'Heatmap'), ('investor', 'Investor'), ('social', 'Social Media')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('zipcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='ZipCodeDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('active_listings', models.IntegerField(default=0)),
                ('avg_rent', models.FloatField(blank=True, null=True)),
                ('median_rent', models.FloatField(blank=True, null=True)),
                ('avg_studio_rent', models.FloatField(blank=True, null=True)),
                ('avg_1br_rent', models.FloatField(blank=True, null=True)),
                ('avg_2br_rent', models.FloatField(blank=True, null=True)),
                ('avg_3br_rent', models.FloatField(blank=True, null=True)),
                ('rent_change_pct', models.FloatField(blank=True, null=True)),
                ('inventory_change_pct', models.FloatField(blank=True, null=True)),
                ('new_listings', models.IntegerField(default=0)),
                ('removed_listings', models.IntegerField(default=0)),
                ('luxury_count', models.IntegerField(default=0)),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='properties.zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('avg_rent', models.FloatField(blank=True, null=True)),
                ('availability_count', models.IntegerField(default=0)),
                ('rent_change_pct', models.FloatField(blank=True, null=True)),
                ('inventory_change_pct', models.FloatField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_metrics', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='propertysnapshot',
            index=models.Index(fields=['snapshot_date'], name='properties__snapsho_3b9307_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertysnapshot',
            unique_together={('property', 'snapshot_date')},
        ),
        migrations.AlterUniqueTogether(
            name='zipcodedailymetrics',
            unique_together={('zipcode', 'date')},
        ),
    ]
