# Generated by Django 6.0.6 on 2026-06-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunitsnapshot',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
