# Generated by Django 6.0.6 on 2026-06-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertyunitsnapshot_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('inventory_up', 'Inventory Up'), ('inventory_down', 'Inventory Down'), ('rent_drop', 'Rent Drop'), ('rent_surge', 'Rent Surge'), ('new_construction', 'New Construction'), ('luxury_launch', 'Luxury Launch'), ('market_heat', 'Market Heat'), ('market_cool', 'Market Cool'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.IntegerField(default=1, help_text='1=info, 2=notable, 3=significant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_to_linkedin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rent', models.IntegerField()),
                ('beds', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('avg_rent', models.FloatField(blank=True, null=True)),
                ('median_rent', models.FloatField(blank=True, null=True)),
                ('active_listings', models.IntegerField(default=0)),
                ('rent_change_pct', models.FloatField(blank=True, null=True)),
                ('inventory_change_pct', models.FloatField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCodeRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rent_growth_rank', models.IntegerField(blank=True, null=True)),
                ('inventory_rank', models.IntegerField(blank=True, null=True)),
                ('demand_rank', models.IntegerField(blank=True, null=True)),
                ('avg_rent_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='management_company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='primary_photo',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('townhome', 'Townhome'), ('condo', 'Condo')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['zipcode', 'city', 'state'], name='properties__zipcode_5a9951_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['management_company'], name='properties__managem_d74005_idx'),
        ),
        migrations.AddIndex(
            model_name='propertysnapshot',
            index=models.Index(fields=['property', 'snapshot_date'], name='properties__propert_f8b544_idx'),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='properties.zipcode'),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property'),
        ),
        migrations.AddField(
            model_name='renthistory',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_history', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='statedailymetrics',
            index=models.Index(fields=['state', 'date'], name='properties__state_f6086b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statedailymetrics',
            unique_together={('state', 'date', 'property_type')},
        ),
        migrations.AddField(
            model_name='zipcoderanking',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='properties.zipcode'),
        ),
        migrations.AddIndex(
            model_name='marketevent',
            index=models.Index(fields=['zipcode', 'event_type'], name='properties__zipcode_8768b6_idx'),
        ),
        migrations.AddIndex(
            model_name='marketevent',
            index=models.Index(fields=['created_at'], name='properties__created_6506dd_idx'),
        ),
        migrations.AddIndex(
            model_name='marketevent',
            index=models.Index(fields=['posted_to_linkedin'], name='properties__posted__a1f04f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyphoto',
            index=models.Index(fields=['property', 'order'], name='properties__propert_61eead_idx'),
        ),
        migrations.AddIndex(
            model_name='renthistory',
            index=models.Index(fields=['property', 'date'], name='properties__propert_bba83a_idx'),
        ),
        migrations.AddIndex(
            model_name='renthistory',
            index=models.Index(fields=['date'], name='properties__date_91c3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='zipcoderanking',
            index=models.Index(fields=['date', 'rent_growth_rank'], name='properties__date_eaa452_idx'),
        ),
        migrations.AddIndex(
            model_name='zipcoderanking',
            index=models.Index(fields=['date', 'inventory_rank'], name='properties__date_1c8fbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zipcoderanking',
            unique_together={('zipcode', 'date')},
        ),
    ]
