# Generated by Django 6.0.6 on 2026-06-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_marketevent_propertyphoto_renthistory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='property',
            name='provider_listing_id',
        ),
    ]
