# Generated by Django 6.0.6 on 2026-06-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysnapshot',
            name='photo_count',
        ),
        migrations.AddField(
            model_name='property',
            name='appliances',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='architectural_style',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cooling',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='exterior_features',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='flooring',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_spaces',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='heating',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='hoa_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='interior_features',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='living_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_features',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='property_tax_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type_detailed',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='sewer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='total_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zestimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertysnapshot',
            name='ad_targets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertysnapshot',
            name='favorite_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertysnapshot',
            name='has_3d_tour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertysnapshot',
            name='listing_sub_type',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propertysnapshot',
            name='page_view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertysnapshot',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertysnapshot',
            name='time_on_zillow',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='PropertyPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('price_per_sqft', models.IntegerField(blank=True, null=True)),
                ('event', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='properties.property')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'date'], name='properties__propert_481a49_idx'), models.Index(fields=['event'], name='properties__event_a25e55_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('level', models.CharField(blank=True, default='', max_length=50)),
                ('grades', models.CharField(blank=True, default='', max_length=50)),
                ('students_count', models.IntegerField(blank=True, null=True)),
                ('teacher_count', models.IntegerField(blank=True, null=True)),
                ('student_teacher_ratio', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='properties.property')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'rating'], name='properties__propert_4fd147_idx'), models.Index(fields=['level'], name='properties__level_32b891_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyTaxHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tax_amount', models.IntegerField()),
                ('value', models.IntegerField()),
                ('year', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_history', to='properties.property')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'date'], name='properties__propert_5936fc_idx'), models.Index(fields=['year'], name='properties__year_c23d4a_idx')],
            },
        ),
    ]
