# Generated by Django 6.0.6 on 2026-06-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_propertysnapshot_photo_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='total_fees',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
