# Generated by Django 6.0.6 on 2026-06-29 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_change_total_fees_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(db_index=True, max_length=255)),
                ('bedrooms', models.FloatField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('living_area', models.IntegerField(blank=True, null=True)),
                ('sold_at', models.CharField(blank=True, max_length=500, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.FloatField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('property_type_detailed', models.CharField(blank=True, default='', max_length=50)),
                ('parking_features', models.JSONField(blank=True, default=list)),
                ('cooling', models.CharField(blank=True, default='', max_length=255)),
                ('heating', models.CharField(blank=True, default='', max_length=255)),
                ('flooring', models.CharField(blank=True, default='', max_length=255)),
                ('appliances', models.JSONField(blank=True, default=list)),
                ('interior_features', models.CharField(blank=True, default='', max_length=500)),
                ('exterior_features', models.CharField(blank=True, default='', max_length=500)),
                ('lot_features', models.CharField(blank=True, default='', max_length=255)),
                ('sewer', models.CharField(blank=True, default='', max_length=255)),
                ('water_source', models.CharField(blank=True, default='', max_length=255)),
                ('architectural_style', models.CharField(blank=True, default='', max_length=255)),
                ('garage_spaces', models.FloatField(blank=True, null=True)),
                ('hoa_fee', models.FloatField(blank=True, null=True)),
                ('total_fees', models.CharField(blank=True, default='', max_length=100)),
                ('property_tax_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zestimate', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('days_on_zillow', models.IntegerField(blank=True, null=True)),
                ('rent_zestimate', models.IntegerField(blank=True, null=True)),
                ('favorite_count', models.IntegerField(blank=True, null=True)),
                ('availability_count', models.IntegerField(blank=True, null=True)),
                ('availability_date', models.CharField(blank=True, default='', max_length=50)),
                ('page_view_count', models.IntegerField(blank=True, null=True)),
                ('time_on_zillow', models.CharField(blank=True, default='', max_length=50)),
                ('listing_sub_type', models.JSONField(blank=True, default=list)),
                ('ad_targets', models.JSONField(blank=True, default=dict)),
                ('status_type', models.CharField(blank=True, default='', max_length=100)),
                ('status_text', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='propertypricehistory',
            name='properties__propert_481a49_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertypricehistory',
            name='properties__event_a25e55_idx',
        ),
        migrations.AlterUniqueTogether(
            name='propertysnapshot',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='propertysnapshot',
            name='properties__snapsho_3b9307_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertysnapshot',
            name='properties__propert_f8b544_idx',
        ),
        migrations.RemoveField(
            model_name='propertyunitsnapshot',
            name='property_snapshot',
        ),
        migrations.RemoveIndex(
            model_name='renthistory',
            name='properties__propert_bba83a_idx',
        ),
        migrations.RemoveIndex(
            model_name='renthistory',
            name='properties__date_91c3c1_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='appliances',
        ),
        migrations.RemoveField(
            model_name='property',
            name='architectural_style',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cooling',
        ),
        migrations.RemoveField(
            model_name='property',
            name='exterior_features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='flooring',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garage_spaces',
        ),
        migrations.RemoveField(
            model_name='property',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='property',
            name='hoa_fee',
        ),
        migrations.RemoveField(
            model_name='property',
            name='interior_features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='living_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lot_features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking_features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='primary_photo',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_tax_rate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type_detailed',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sewer',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_fees',
        ),
        migrations.RemoveField(
            model_name='property',
            name='water_source',
        ),
        migrations.RemoveField(
            model_name='property',
            name='year_built',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zestimate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zpid',
        ),
        migrations.AddField(
            model_name='property',
            name='has_3d_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_3d_tour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='lotId',
            field=models.CharField(db_index=True, default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='parcel_id',
            field=models.CharField(db_index=True, default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property'),
        ),
        migrations.AddField(
            model_name='unitsnapshot',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='properties.unit'),
        ),
        migrations.RemoveField(
            model_name='propertypricehistory',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertysnapshot',
            name='property',
        ),
        migrations.DeleteModel(
            name='PropertyUnitSnapshot',
        ),
        migrations.RemoveField(
            model_name='renthistory',
            name='property',
        ),
        migrations.DeleteModel(
            name='PropertyPriceHistory',
        ),
        migrations.DeleteModel(
            name='PropertySnapshot',
        ),
        migrations.DeleteModel(
            name='RentHistory',
        ),
    ]
