# Generated by Django 6.0.6 on 2026-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_unit_unitsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='zpid',
            field=models.CharField(db_index=True, default='1', max_length=255),
            preserve_default=False,
        ),
    ]
