# Generated by Django 6.0.6 on 2026-06-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_zpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lotId',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
