import scrapy


class ZillowListing(scrapy.Item):
    source = scrapy.Field()
    lotId = scrapy.Field()
    zpid = scrapy.Field()
    detail_url = scrapy.Field()
    building_name = scrapy.Field()
    is_building = scrapy.Field()
    address = scrapy.Field()
    street = scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    zipcode = scrapy.Field()
    latitude = scrapy.Field()
    longitude = scrapy.Field()


class ZillowDetailItem(scrapy.Item):
    zpid = scrapy.Field()
    lotId = scrapy.Field()
    parcel_id = scrapy.Field()
    bedrooms = scrapy.Field()
    bathrooms = scrapy.Field()
    living_area = scrapy.Field()
    lot_size = scrapy.Field()
    year_built = scrapy.Field()
    property_type_detailed = scrapy.Field()
    parking_features = scrapy.Field()
    cooling = scrapy.Field()
    heating = scrapy.Field()
    flooring = scrapy.Field()
    appliances = scrapy.Field()
    interior_features = scrapy.Field()
    exterior_features = scrapy.Field()
    lot_features = scrapy.Field()
    sewer = scrapy.Field()
    water_source = scrapy.Field()
    architectural_style = scrapy.Field()
    garage_spaces = scrapy.Field()
    hoa_fee = scrapy.Field()
    total_fees = scrapy.Field()
    zestimate = scrapy.Field()
    property_tax_rate = scrapy.Field()
    description = scrapy.Field()
    price_history = scrapy.Field()
    tax_history = scrapy.Field()
    schools = scrapy.Field()
    units = scrapy.Field()
