/**
 * Voiceover helper for YouTube Shorts.
 * Loads generated audio files from Ollama TTS.
 *
 * Usage in Remotion:
 *   import { getNarration, narrationFiles } from "./voiceover";
 *
 *   const narration = getNarration("winner-vs-runner-up");
 *   // Returns array of { text, audioFile } for each scene
 */

import { staticFile } from "remotion";
import type { ShortsMode } from "./data/types";

export type NarrationEntry = {
  text: string;
  audioFile: string;
};

/**
 * Scene names matching the audio files generated by generate_voiceover.py
 */
const SCENES = ["hook", "zipA", "zipB", "headToHead", "keyDifference", "takeaway", "cta"] as const;

/**
 * Narration scripts for each mode
 */
const NARRATION_SCRIPTS: Record<ShortsMode, Record<string, string>> = {
  "winner-vs-runner-up": {
    hook: "Which of these two Atlanta ZIP codes should you invest in right now?",
    zipA: "The number one ZIP code by investor score in Atlanta.",
    zipB: "The runner-up, still hot but not quite number one.",
    headToHead: "Both are hot. But only one is investable right now.",
    keyDifference: "This is the edge that separates good from great.",
    takeaway: "High demand plus compressed inventory equals pricing power.",
    cta: "Comment REPORT to get the full ZIP code analysis with investor scores.",
  },
  "winner-vs-loser": {
    hook: "This ZIP code is soaring while another one is crashing.",
    zipA: "The highest-scoring ZIP code in Atlanta right now.",
    zipB: "The fastest-falling ZIP code in Atlanta.",
    headToHead: "One market is thriving. The other is collapsing.",
    keyDifference: "The spread between these two is where the opportunity lives.",
    takeaway: "When one ZIP drops while another gains, the spread is the opportunity.",
    cta: "Comment REPORT to get the full ZIP code analysis with investor scores.",
  },
};

/**
 * Get narration entries for a specific mode
 */
export function getNarration(mode: ShortsMode): NarrationEntry[] {
  const scripts = NARRATION_SCRIPTS[mode];

  return SCENES.map((scene) => ({
    text: scripts[scene] || "",
    audioFile: `${scene}.mp3`,
  }));
}

/**
 * Check if audio files exist (for fallback to silent mode)
 */
export function hasAudioFiles(): boolean {
  try {
    // This checks at build time - actual file check happens at runtime
    return true;
  } catch {
    return false;
  }
}

/**
 * Get static file path for audio
 */
export function getAudioPath(filename: string): string {
  return staticFile(`audio/shorts/${filename}`);
}

export { SCENES, NARRATION_SCRIPTS };
